<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Systemd Files</string>
    <key>scopeName</key>
    <string>source.systemd</string>
    <key>fileTypes</key>
    <array>
      <string>service</string>
      <string>path</string>
      <string>mount</string>
      <string>automount</string>
      <string>target</string>
      <string>scope</string>
      <string>slice</string>
      <string>snapshot</string>
      <string>socket</string>
    </array>
    <key>uuid</key>
    <string>9db82014-225f-40fe-b087-d5c2915d1c51</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#section</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>boolean</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.language.boolean.systemd</string>
            <key>match</key>
            <string>\b(?i:yes|no|0|1|true|false)\b</string>
          </dict>
        </array>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.line.hash.systemd</string>
            <key>match</key>
            <string>^(#).*$\n?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.systemd</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.line.semi-colon.systemd</string>
            <key>match</key>
            <string>^(;).*$\n?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.systemd</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>section</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.section.systemd</string>
            <key>begin</key>
            <string>\[\s*([\w_-]+)(?:\s+((")(?:[^"\\]|\\["\\])*("))|\.([\w_-]+))?\s*\]</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.section.systemd</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.section.subsection.systemd</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.section.subsection.begin.systemd</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.section.subsection.end.systemd</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>entity.name.section.subsection.systemd</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\[)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#value_pair</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.quoted.double.systemd</string>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.systemd</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.systemd</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>constant.character.escape.systemd</string>
                <key>match</key>
                <string>\\[ntb"\\]</string>
              </dict>
              <dict>
                <key>name</key>
                <string>invalid.illegal.unknown-escape.systemd</string>
                <key>match</key>
                <string>\\.</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>value_pair</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.value-pair.section-item.systemd</string>
            <key>begin</key>
            <string>^\s*([-\w]+)\s*(=-|=)\s*</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.definition.systemd</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.key-value.systemd</string>
              </dict>
            </dict>
            <key>end</key>
            <string>$|(?=[#;])</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#boolean</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>